apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: streamflix-monitor
  namespace: monitoring
spec:
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: streamflix
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s
